SciSharp/NumSharp

- src/NumSharp/Extensions/NdArray.ARange.cs
- test/NumSharp.UnitTest/Extensions/NdArray.Mean.Test.cs
- Build failed because NDim could not be set (missing setter?)
- test of mean shows 1 very strange behaviour 
- when debugging all is fine (mean is 2.5)
- when running test without debug --> mean is inf????
- will rise an issue
> Build failed and 1 Test failed

- src/NumSharp/Extensions/NdArray.Dot.cs
- test/NumSharp.UnitTest/Extensions/NdArray.Dot.Test.cs
- we keep issue because just working for double arrays
> Added dot method for two 1D arrays of double

- src/NumSharp/Extensions/NdArray.Array.cs
- src/NumSharp/Extensions/NdArray.Dot.cs
- src/NumSharp/NdArray.ExtensionLinking.cs
- test/NumSharp.UnitTest/Extensions/NdArray.Dot.Test.cs
- Dot between two 1D complex arrays possible
- Dot between two 2D doubles arrays possible
- Dot between one 1D double array and a scalar
> Extended Dot Method

- src/NumSharp/Extensions/NdArray.AsMatrix.cs
- src/NumSharp/Matrix.cs
- src/NumSharp/NdArray.ExtensionLinking.cs
- test/NumSharp.UnitTest/Extensions/NdArray.AsMatrix.Test.cs
- test/NumSharp.UnitTest/Matrix.Test.cs
- wanted to bring asmatrix --> for this need to bring Matrix class 
- related to issue #27 
- related to issue #28
> added Matrix class and asMatrix method from numpy

- src/NumSharp/Matrix.cs
- src/NumSharp/Operations/Matrix.Addition.cs
- src/NumSharp/Operations/Matrix.Substraction.cs
- src/NumSharp/Operations/NdArray.Addition.cs
- src/NumSharp/Operations/NdArray.Multiplication.cs
- src/NumSharp/Operations/NdArray.Substraction.cs
- test/NumSharp.UnitTest/Matrix.Test.cs
- test/NumSharp.UnitTest/Operations/Matrix.Addition.Test.cs
- test/NumSharp.UnitTest/Operations/Matrix.Substraction.Test.cs
- test/NumSharp.UnitTest/Operations/NDArray.Addition.Test.cs
- test/NumSharp.UnitTest/Operations/NDArray.Multiplication.Test.cs
- test/NumSharp.UnitTest/Operations/NDArray.Substraction.Test.cs
- support for "+","-","*" for NDArray
- support for "+","-" for Matrix
- Added some methods also for complex numbers 
- check now string syntax in Matrix constructor
> Numerical Operator support

- src/NumSharp/Extensions/NdArray.Dot.cs
- src/NumSharp/Shared/Operation.MatrixMultiplication.Complex.cs
- src/NumSharp/Shared/Operation.MatrixMultiplication.Double.cs
- src/NumSharp/Shared/Operation.MatrixMultiplication.Int32.cs
- src/NumSharp/Shared/Operation.MatrixMultiplication.Int64.cs
- src/NumSharp/Shared/Operation.MatrixMultiplication.Quaternion.cs
- src/NumSharp/Shared/Operation.MatrixMultiplication.decimal.cs
- src/NumSharp/Shared/Operation.MatrixMultiplication.float.cs
- src/NumSharp/Shared/Operation.ScalarProduct1D.Double.cs
- src/NumSharp/Shared/Operation.ScalarProduct1D.Int32.cs
- src/NumSharp/Shared/Operation.ScalarProduct1D.Int64.cs
- src/NumSharp/Shared/Operation.ScalarProduct1D.decimal.cs
- src/NumSharp/Shared/Operation.ScalarProduct1D.float.cs
- test/NumSharp.UnitTest/Extensions/NdArray.Dot.Test.cs
- test/NumSharp.UnitTest/Operations/NDArray.Multiplication.Test.cs
- element wise operations works now for new NDArray
- Dot Method and Matrix Multiplication now works for NDArray with NDim = 2
- Unit tests mostly rewritten
> Rewriting Operations and Dot method done 

- test/NumSharp.Benchmark/ArrayTester.cs
- test/NumSharp.Benchmark/Program.cs
- just to see if 1D strategy is better or worse than jagged arrays
> Add really basis array benchmark test

- src/NumSharp/NdArray.ExtensionLinking.cs
- src/NumSharp/NdArray.cs
- src/NumSharp/Shared/Operation.MatrixMultiplication.Double.cs
- test/NumSharp.UnitTest/Extensions/NdArray.Dot.Test.cs
- test/NumSharp.UnitTest/NdArray.Test.cs
- matrix Multiplication did wrong dimension multiplication
- now all works numpy like
- ToString() method does now give output like numpy for 2D arrays (matrix)
> Corrected Matrix Multiplication 

- src/NumSharp/NdArray.cs
- test/NumSharp.UnitTest/NdArray.Test.cs
- the ToDotNetArray method for better integration with other frameworks
- very non generic at moment 
- just static mapping with switch case
> Add ToDotNetArray method for 1D,2D,3D

- src/NumSharp/Extensions/NdArray.Inv.cs
- src/NumSharp/Operations/NdArray.Addition.cs
- src/NumSharp/Shared/Operation.MatrixDecomposition.Double.cs
- src/NumSharp/Shared/Operation.MatrixInv.Double.cs
- src/NumSharp/Shared/Operation.MatrixMultiplication.Complex.cs
- src/NumSharp/Shared/Operation.MatrixMultiplication.Int32.cs
- src/NumSharp/Shared/Operation.MatrixMultiplication.Int64.cs
- src/NumSharp/Shared/Operation.MatrixMultiplication.Quaternion.cs
- src/NumSharp/Shared/Operation.MatrixMultiplication.decimal.cs
- src/NumSharp/Shared/Operation.MatrixMultiplication.float.cs
- src/NumSharp/Shared/Operation.ScalarProduct1D.Complex.cs
- src/NumSharp/Shared/Operation.ScalarProduct1D.Quaternion.cs
- test/NumSharp.UnitTest/Extensions/NdArray.Dot.Test.cs
- test/NumSharp.UnitTest/Extensions/NdArray.Inv.Test.cs
- add method to inverse a 2D array
- including unit tests 
- some bug fixes for complex matrix multiplication
> Add Inverse Matrix method for 2D array

- src/NumSharp/Extensions/NdArray.Sqrt.cs
- test/NumSharp.UnitTest/Extensions/NdArray.Sqrt.Test.cs
> Add NdArray Sqrt

- test/NumSharp.Benchmark/Program.cs
- was my fault sorry .... 
- clicked wrong button in VS Code and VS Code did not clearly shows merge conflict exist
> Fixed merge Conflict (did not see in VSC)

- Benchmark.ps1
- test/NumSharp.Benchmark/Program.cs
- related to #93 
- Program class do now a small check for CLI arguments (run tests depending on them)
- added Powershell Skript for better use 
- simple start powershell 
- enter ./Benchmark.ps1
- `Start-Benchmark -Test NDArray`
> Add Command Line check for benchmark

- docs/index.rst
- src/NumSharp.Python/numpy.arange.cs
- related #70 
- just as cover to make people understand why we do it
> Just add some text to doc 

- docs/index.rst
- docs/user-docs/NDArray.Creation.md
- docs/user-docs/overview.md
- src/NumSharp/LinearAlgebra/NdArray.Transpose.cs
- test/NumSharp.UnitTest/Docs/NDArray.Creation.cs
- test/NumSharp.UnitTest/Docs/NDArray.LinAlgebra.cs
- no changes in code 
- #70 related
> Doc : just add some more text to doc 

- src/NumSharp/LinearAlgebra/NdArray.Transpose.cs
- test/NumSharp.UnitTest/LinearAlgebra/NdArray.Transpose.cs
- very simple (as explained in #117 )
- no view (keep #117  open)
- Do not worry (documentation stuff is in an other branch in my repo - so i can go on experiment with doc but still support some issues)
> feat : Add simple Transpose method

- src/NumSharp.Core/Creation/NumPy.array.cs
- src/NumSharp.Core/Exceptions/IncorrectShapeException.cs
- src/NumSharp.Core/LinearAlgebra/NdArray.Dot.cs
- src/NumSharp.Core/LinearAlgebra/NdArray.multi_dot.cs
- src/NumSharp.Core/LinearAlgebra/NumPy.dot.cs
- test/NumSharp.UnitTest/LinearAlgebra/NdArray.Dot.Test.cs
- test/NumSharp.UnitTest/LinearAlgebra/NdArray.Inv.Test.cs
- test/NumSharp.UnitTest/LinearAlgebra/NdArray.multi_dot.Test.cs
- now dot without generics 
- adapted the unit Tests also
> Redesigned dot method to pure non generic method

- src/NumSharp.Core/Exceptions/IncorrectTypeException.cs
- src/NumSharp.Core/LinearAlgebra/NdArray.Inv.cs
- test/NumSharp.UnitTest/LinearAlgebra/NdArray.Inv.Test.cs
- inv and unit tests now work properly without generics
> Redesign : inv now non generic

- src/NumSharp.Core/Creation/NdArray.MakeGeneric.cs
- src/NumSharp.Core/Generics/NDArrayGeneric.cs
- src/NumSharp.Core/LinearAlgebra/NdArray.Transpose.cs
- test/NumSharp.UnitTest/Creation/NdArray.MakeGeneric.Test.cs
- so we can have generic and non generic easily with easy casting
> Feat : Create generic NDArrays by non generic.

- src/NumSharp.Core/Creation/NdArray.Ones.cs
- src/NumSharp.Core/Creation/NdArray.VStack.cs
- src/NumSharp.Core/Creation/NumPy.linspace.cs
- src/NumSharp.Core/Creation/NumPy.ones.cs
- src/NumSharp.Core/LinearAlgebra/NdArray.Transpose.cs
- src/NumSharp.Core/NDStorage.cs
- src/NumSharp.Core/Operations/NdArray.Addition.cs
- src/NumSharp.Core/Operations/NdArray.Multiplication.cs
- src/NumSharp.Core/Operations/NdArray.Substraction.cs
- src/NumSharp.Core/Selection/NDArray.Indexing.cs
- test/NumSharp.UnitTest/Operations/NDArray.Addition.Test.cs
- test/NumSharp.UnitTest/Operations/NDArray.Multiplication.Test.cs
- test/NumSharp.UnitTest/Operations/NDArray.Substraction.Test.cs
- #136 
- redesign some methods for non generics 
- unit tests for operations now check the non generic ndarray
> Some modifications for non generics

- src/NumSharp.Core/Creation/NdArray.Eye.cs
- src/NumSharp.Core/LAPACK.cs
- src/NumSharp.Core/LinearAlgebra/NdArray.QR.cs
- src/NumSharp.Core/Operations/NdArray.Multiplication.cs
- test/NumSharp.UnitTest/LinearAlgebra/NdArray.QR.Test.cs
- first LAPACK based method --> QR! 
- related to #145
> First LAPACK based method qr

- src/NumSharp.Core/LAPACK.cs
- src/NumSharp.Core/LinearAlgebra/NdArray.LstSq.cs
- test/NumSharp.UnitTest/LAPACK/dgels.cs
- test/NumSharp.UnitTest/LinearAlgebra/NdArray.LstSq.Test.cs
- first meaningful use of LAPACK
- related to #144 
- test include the test of python doc https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.lstsq.html
> Add lstsq finally! 

- ValidatePackage.ps1
- test/NumSharp.ConsumePackage/NumSharp.ConsumePackage.csproj
- test/NumSharp.ConsumePackage/Program.cs
- related to #150 
- seems the package already can be consumed
> Added project for check the package consuming

- src/NumSharp.Core/Creation/NdArray.HStack.cs
> Fix : HStack method was fixed (dimension instead of dimofset)

- src/NumSharp.Core/Creation/NdArray.Mgrid.cs
- src/NumSharp.Core/Creation/NdArray.Roll.cs
- test/NumSharp.UnitTest/Creation/NdArray.Mgrid.Test.cs
- test/NumSharp.UnitTest/Creation/NdArray.Roll.Test.cs
- related to #165 
- most apis for issue 165 now exist
> Add roll and mgrid APIs as new NDArray methods

- src/NumSharp.Core/Creation/NdArray.Roll.cs
- src/NumSharp.Core/Creation/np.mgrid.cs
- test/NumSharp.UnitTest/Creation/NdArray.Roll.Test.cs
- test/NumSharp.UnitTest/Scripts/water.cs
- some "short cuts" are missing (C# do not offer operator **2)
- syntax 100% adapted to C# 
- **UNTESTED!** 
- compiled but not tested
- related to #165
> Add water equation - untested just syntax is correct now

- .vscode/launch.json
- NumSharp.sln
- src/NumSharp.Core/Casting/Implicit/NdArray.Implicit.Array.cs
- src/NumSharp.Core/NumSharp.Core.csproj
- test/NumSharp.Examples/ShallowWater/Program.cs
- test/NumSharp.Examples/ShallowWater/ShallowWater.csproj
- test/NumSharp.UnitTest/Casting/NDArray.ImplicitCasts.cs
- test/NumSharp.UnitTest/LAPACK/dgesvd.cs
- test/NumSharp.UnitTest/Selection/NDArray.Enumerator.Test.cs
- related to #174 
- related to #165 
- the "[1,2,3;4,5,6]" does not work anymore ( we can not decide if parsed or scalar cast)
- too dangerous 
- better suggest --> np.array("[1,2;3,4]")
> Add example and fixed 174

- src/NumSharp.Core/Random/np.random.randn.cs
- test/NumSharp.UnitTest/Creation/np.random.normal.Test.cs
- related to issue #177 
- did fix 
- extended unit test
> Fix : random.normal returns true shaped array

- .appveyor.yml
- ExecuteUnitTests.ps1
- add appveyor.yaml 
- related to #179 
- experimented a lot :)
> Style : Improve output logging of unit tests

- src/NumSharp.Core/Extensions/LinqExtensions.cs
- src/NumSharp.Core/Extensions/ndarray.argsort.cs
numpy.argsort is implemented
Please see issue #197
> #197[implemented] ndarray.argsort algorithm implemented

- src/NumSharp.Core/NDStorage.cs
- test/NumSharp.UnitTest/Selection/NDArray.Indexing.Test.cs
2) Add UnitTest for NDArrayAccess3Dim
> 1)  Fix Bug #203. by changing GetData in NDStorage.cs.

- src/NumSharp.Core/Creation/broadcast.cs
- src/NumSharp.Core/Creation/broadcast_arrays.cs
- src/NumSharp.Core/Creation/np.array.cs
- test/NumSharp.UnitTest/Creation/np.broadcast_arrays.Test.cs
2) Reload new NDArray Constractor for T[,] array
> 1) implemented UnitTest for np.broadcast_arrays

- .editorconfig
It will be great to apply official [dotnet-format tool](https://github.com/dotnet/format) as well : )
> .editorconfig from https://github.com/dotnet/format

- src/NumSharp.Core/Selection/NDArray.Indexing.cs
- src/NumSharp.Core/Slice.cs
- test/NumSharp.UnitTest/Selection/NDArray.Indexing.Test.cs
Damn it, Visual Studio did a white space conversion. Very inconvenient.
> Slice: implemented numpy slice notation

- test/NumSharp.UnitTest/NumSharp.UnitTest.csproj
ref: https://github.com/SciSharp/NumSharp/pull/247
This change supports using external files in tests.
example:
```cs
var loadedArr = np.Load<int[]>(@"data/some_npy_file.npy");
```
> Fix failing test that cannot load files

- src/NumSharp.Core/APIs/np.load.cs
- src/NumSharp.Core/APIs/np.save.cs
- test/NumSharp.UnitTest/np.save_load.Test.cs
fix: https://github.com/SciSharp/NumSharp/issues/224
> Support load and save,  value type float and double

- src/NumSharp.Core/Shape.cs
- src/NumSharp.Core/Slice.cs
- src/NumSharp.Core/View/ViewStorage.cs
- test/NumSharp.UnitTest/Selection/NDArray.Indexing.Test.cs
- test/NumSharp.UnitTest/View/ViewStorage.Test.cs
I still can't believe how easy it was to generalize this to N dimensions
> ViewStorage: implemented general N-Dimensional slicing

- src/NumSharp.Core/Slice.cs
- src/NumSharp.Core/View/ViewStorage.cs
- test/NumSharp.UnitTest/Selection/NDArray.Indexing.Test.cs
- test/NumSharp.UnitTest/View/ViewStorage.Test.cs
ToString implements nice pretty printing. It is also an example how to use slicing with dimensionality reduction to solve N-dimensional problems.
ToString(flat:true)
ToString()
> ViewStorage: implemented a nice ToString method

- test/NumSharp.UnitTest/Selection/NDArray.Indexing.Test.cs
- test/NumSharp.UnitTest/np.save_load.Test.cs
SaveAndLoadWithNpyFileExt pointed to aboslute C:\TEMP folder. Now it use working directory.
Output from python added as comment to AssignGeneric*Slice1 unit tests as expected output.
> Change SaveAndLoadWithNpyFileExt unit test to use local relative path

- src/NumSharp.Core/APIs/np.math.cs
- src/NumSharp.Core/Math/NDArray.negative.cs
- src/NumSharp.Core/Math/NDArray.positive.cs
- test/NumSharp.UnitTest/Math/NDArray.negative.Test.cs
- test/NumSharp.UnitTest/Math/NDArray.positive.Test.cs
I'm replacing the cloning at the beggining of the method to the way it is being used in other mathops.
Do not merge yet.
> Added np.positive and np.negative

- src/NumSharp.Core/Random/np.random.rand.cs
- test/NumSharp.UnitTest/Random/np.random.rand.Test.cs
- test/NumSharp.UnitTest/Random/np.random.uniform.Test.cs
* Added np.random.rand(...)
* Added np.random.random_sample(...)
* Added unit tests for changes above
* Added unit tests for np.random.uniform
> Implementation of np.random.rand, np.random.random_sample

- test/NumSharp.UnitTest/Random/Randomizer.Tests.cs
- test/NumSharp.UnitTest/Random/np.random.normal.Test.cs
- test/NumSharp.UnitTest/Random/np.random.rand.Test.cs
- test/NumSharp.UnitTest/Random/np.random.randint.Test.cs
- test/NumSharp.UnitTest/Random/np.random.shuffle.Test.cs
- test/NumSharp.UnitTest/Random/np.random.uniform.Test.cs
Moved files related to unit-testing np.random from Creation folder to Random.
Changed namespace of files related to unit-testing np.random to RandomSampling.
> Fixed namespaces and file locations for random tests

- src/NumSharp.Core/Random/np.random.choice.cs
- src/NumSharp.Core/Sorting_Searching_Counting/np.searchsorted.cs
- test/NumSharp.UnitTest/Random/np.random.choice.Test.cs
Random sampling with weighted probabilities.
Missing functionalit:
* Sampling without replacement
* Output in specified shapes
> Basic np.random.choice functionality

- src/NumSharp.Core/RandomSampling/np.random.choice.cs
- src/NumSharp.Core/RandomSampling/np.random.cs
- test/NumSharp.UnitTest/Random/np.random.seed.Test.cs
Fixed the choice method so that it respects the seed of the random st…ate it is running in.
Fixed the Seed attribute from NumPyRandom so that it returns the seed value that was specified in the ctor. 
Added unit tests for testing the seed state's consistency.
> Fixing the consistency of seed in the random choice.
