src/NumSharp/Extensions/NdArray.Convolve.cs, test/NumSharp.UnitTest/Extensions/NdArray.Convolve.Test.cs
=> Add equalent np.convolve (just full mode)

README.md, src/NumSharp/Extensions/NdArray.Convolve.cs, test/NumSharp.UnitTest/Extensions/NdArray.Convolve.Test.cs
- behaviour is like on numpy documentation 
- Tests take the examples from https://www.numpy.org/devdocs/reference/generated/numpy.convolve.html
- Convolve now is part of existing APIs in Readme
=> Finished Convolve + Added to Readme

src/NumSharp/Extensions/NdArray.HStack.cs, test/NumSharp.UnitTest/Extensions/NdArray.HStack.Test.cs
- implemented very basis of #10 
- it merges 2 arrays to a 3rd one
- slightly different from numpy since hstack on numpy is not an method but global function 
- keep issue open until rest is implemented according to https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.hstack.html
=> Add HStack for two 1D Arrays which append to a new 3rd one

src/NumSharp/Extensions/NdArray.ARange.cs, src/NumSharp/Extensions/NdArray.ArgMax.cs, src/NumSharp/Extensions/NdArray.Convolve.cs, src/NumSharp/Extensions/NdArray.Delete.cs, src/NumSharp/Extensions/NdArray.Dot.cs, src/NumSharp/NdArray.ExtensionLinking.cs
After some experiments and playing around find that extension methods are better for beginning. 
So we can implement all APIs for double first and later come with int, float, complex, quaternion, etc. 
Since we can decide which generic Type we want to implement --> easy to use. 
In order to use them in Powershell (I will add maybe script in UnitTest project simple to show) added a file called "NdArray.ExtensionLinking.cs" which honestly just "shows" all extension methods as true methods.
=> Back to Extension methods 

src/NumSharp/Extensions/NdArray.Eye.cs, test/NumSharp.UnitTest/Extensions/NdArray.Eye.Test.cs
- the eye method is until now just constructed for 2D arrays so matrix
- need to generalize it to ND
- test for normal diagonal, -2 and +2 shifted diagonal
=> Add eye method for 2D arrays (not higher dimension)

src/NumSharp/NdArray.cs, test/NumSharp.UnitTest/NdArray.Test.cs
- followed suggest in issue with "ToDotNetArray<double[][]>() strategy 
- could give power to do array and type cast with one method
e.g. var np = NDArray< double >().ARange(9).Reshape(3,3).ToDotNetArray< int [][] >();
=> Changed dynamic output of ToDotNetArray method to generic interface 

src/NumSharp/NdArray.cs, test/NumSharp.UnitTest/NdArray.Test.cs
- for 2D arrays so matrix 
- until now quite complex since all numbers converted to string, digits before "." and after are counted and dots shall be all at some location in matrix (column like) in this string
- @Oceania2018 you can try it on Visual Studio :D if format still now right let me know 
- just tested it for 2D arrays in Powershell
=> Improved Format of ToString()

src/NumSharp.Core/Interfaces/IStorage.cs, src/NumSharp.Core/NDArrayGeneric.cs, src/NumSharp.Core/NdArray.cs, test/NumSharp.UnitTest/Creation/NdArray.Array.Test.cs
- The NDArray is now extrem dynamic and flexible 
- The only thing I find annoyingful at moment --> indexing
- I mean **true** indexing like np1[1,2,3] and not via Data method
- we can not indexing in a gentle way since the output is always different (int, double,...)
- This i think is extrem nice with our generic old class (but I dont want to go back to old class…)
- my idea : NumSharp.Generic.NDArray which is 100% a child of NumSharp.Core.NDArray 
- check the code we can use 100% of the Core methods but the indexing here looks gentle. 
- every user shall decide by theirselves which is better for their project 
- for Pandas.NET sure we go with NumSharp.Core.NDArray
=> Try to bring generic and non generic together in 2 different classes

src/NumSharp.Core/Interfaces/IShape.cs, src/NumSharp.Core/Interfaces/IStorage.cs
- no big issue 
- just to proper planning and better, clear use of storage
=> Add interfaces for proper planning

NumSharp.sln, src/NumSharp.Core/Math/NdArray.Mean.cs, src/NumSharp.Core/Math/NdArray.Std.cs, src/NumSharp.Core/NumSharp.Core.csproj, test/NumSharp.UnitTest/Creation/np.random.normal.Test.cs, test/NumSharp.UnitTest/Extensions/NDArray.Std.Test.cs, test/NumSharp.UnitTest/NumSharp.UnitTest.csproj
- i dont know when but seems was removed before 
- related to #9 
- extended unit Tests 
- csproj was adapted (VS Code debugger did not work before -.- )
=> Add Std api as method again

.vscode/launch.json, ExecuteBuild.ps1, src/NumSharp.Core/LinearAlgebra/LAPACK.Provider/LAPACK.NetLib.cs, src/NumSharp.Core/LinearAlgebra/LAPACK.cs, src/NumSharp.Core/LinearAlgebra/np.LAPACK.cs, src/NumSharp.Core/NDStorage.cs
- just strategy was implemented - not the MKL 
- MKL open
- related to #116 
- some style restructure related to this
=> Add LAPACK Provider Strategy (MKL not!!! implemented yet)

src/NumSharp.Core/NdArray.cs
In the override of `Equals` method of `NDArray`, while testing, I noticed that was throwing for any other object than `NDArray`. Moreover, it catches every exception while nothing Exceptional is should be going on .
=> [Fixed] NdArray Equals methods throws for any object comparison other than NDArray and does not handle any exception thrown.

src/NumSharp.Core/Creation/np.arange.cs, test/NumSharp.UnitTest/Creation/np.arange.Test.cs, test/NumSharp.UnitTest/Selection/NDArray.AMax.Test.cs
Using doubles could cause IndexOutOfRangeException. Unit tests added to test it no long happens.
=>  Fix: Avoid IndexOutOfRangeException in arange method

src/NumSharp.Core/APIs/np.save.cs, test/NumSharp.UnitTest/np.save_load.Test.cs
Python numpy cannot load a npy file that generated by NumSharp.np.Save method.
Because shape shows `(R)` not `(R,)`.
So I changed save with shape `(R,)`.
=> Make save method compatible with numpy's npy

src/NumSharp.Core/Backends/TypedArrayStorage.cs, src/NumSharp.Core/NumSharp.Core.csproj, src/NumSharp.Core/NumSharp.Core.csproj.DotSettings, src/NumSharp.Core/Shape.cs, src/NumSharp.Core/Slice.cs, src/NumSharp.Core/View/ViewStorage.cs, test/NumSharp.UnitTest/View/ViewStorage.Test.cs
I think the test speaks volumes: 
[TestMethod]
public void NestedView_1D()
{
var data = new TypedArrayStorage(new int[] { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 });
// return identical view
var identical = new ViewStorage(data, ":");
Assert.AreEqual(new Shape(10), identical.Shape);
var view1 = new ViewStorage(identical, "1:9");
Assert.AreEqual(new Shape(8), view1.Shape);
AssertAreEqual(new int[] { 1, 2, 3, 4, 5, 6, 7, 8, }, view1.GetData());
var view2 = new ViewStorage(view1, "::-2");
Assert.AreEqual(new Shape(4), view2.Shape);
AssertAreEqual(new int[] { 8, 6, 4, 2, }, view2.GetData());
var view3 = new ViewStorage(view2, "::-3");
Assert.AreEqual(new Shape(2), view3.Shape);
AssertAreEqual(new int[] { 2, 8 }, view3.GetData());
// all must see the same modifications, no matter if original or any view …
=> ViewStorage: implemented 1-d slicing with step (nested views)

src/NumSharp.Core/Creation/NdArray.MakeGeneric.cs, src/NumSharp.Core/Generics/NDArrayGeneric.cs, src/NumSharp.Core/Selection/NDArray.Indexing.cs, src/NumSharp.Core/Slice.cs, src/NumSharp.Core/View/ViewStorage.cs, test/NumSharp.Benchmark/NDArraySliceAndSpanTester.cs, test/NumSharp.Benchmark/NumSharp.Benchmark.csproj, test/NumSharp.Benchmark/Program.cs, test/NumSharp.UnitTest/Selection/NDArray.Indexing.Test.cs
Slice assign for generic NDArray<T> added (very primitiv implementation, limited tested and does not support untyped NDArray)
Slice(1, -1) support added (limited test added)
Slice inteface added to generic NDArray<T>.
Slice benchmark tests added and debug of benchmark made easier
=> Slice assign for generic NDArray<T> added

src/NumSharp.Core/NumSharp.Core.csproj
Support for creating ci build and prerelease versions via
dotnet pack --version-suffix "ci-x"
while keeping the ability to edit the package inforamtion via Visual Studio GUI
=> Support for dotnet pack --version-suffix

src/NumSharp.Core/APIs/np.fromfile.cs, src/NumSharp.Core/APIs/np.tofile.cs, src/NumSharp.Core/Backends/Default/Math/Default.Divide.cs, src/NumSharp.Core/Backends/TypedArrayStorage.cs, test/NumSharp.UnitTest/APIs/np.math.Test.cs, test/NumSharp.UnitTest/APIs/np.tofromfile.Test.cs
Includes unit tests for uint16 tofile/fromfile/divide.
Also includ workaround problem detecting correct uint16/int16 type in switch/case statement.
Using C# 7.3 compiler detect uint16/int16 array type incorrectly.  Work arround added for uint16/int16. Same problems also seems to exist for other unsigned/signed combinations:
https://developercommunity.visualstudio.com/content/problem/578478/switch-case-on-int-and-uint-type-alsways-pick-int.html
=>  uint16 support for tofile and fromfile and uint16 divide

src/NumSharp.Core/Manipulation/np.expand_dims.cs, test/NumSharp.UnitTest/Manipulation/NDArray.expand_dims.Test.cs
Let me know if you think there is a better/faster way to handle the parsing of the reshape
=> Added implementation of np.expand_dims(NDArray a, int axis)

src/NumSharp.Core/APIs/np.logic.cs, src/NumSharp.Core/APIs/np.math.cs, src/NumSharp.Core/APIs/np.statistics.cs, src/NumSharp.Core/Backends/ArrayStorage.cs, src/NumSharp.Core/Backends/BackendFactory.cs, src/NumSharp.Core/Backends/Default/ArrayManipulation/Default.Cast.cs, src/NumSharp.Core/Backends/Default/ArrayManipulation/Default.Transpose.cs, src/NumSharp.Core/Backends/Default/Math/Default.Sum.cs, src/NumSharp.Core/Backends/IStorage.cs, src/NumSharp.Core/Backends/ITensorEngine.cs, src/NumSharp.Core/Backends/NDArray.cs, src/NumSharp.Core/Casting/Implicit/NdArray.Implicit.ValueTypes.cs, src/NumSharp.Core/Casting/NdArrayFromMultiDimArr.cs, src/NumSharp.Core/Creation/NDArray.Copy.cs, src/NumSharp.Core/Creation/NdArray.Ones.cs, src/NumSharp.Core/Creation/NdArray.Scalar.cs, src/NumSharp.Core/Creation/np.ones.cs, src/NumSharp.Core/Creation/np.ones_like.cs, src/NumSharp.Core/Creation/np.zeros.cs, src/NumSharp.Core/Manipulation/np.asscalar.cs, src/NumSharp.Core/Manipulation/np.reshape.cs, test/NumSharp.UnitTest/Manipulation/NDArray.astype.Test.cs
Hey, commit's descriptions describe exactly what was done.
`np.ones`, `np.zeros` were rewritten to fallback into a single method and `np.ones` implementation fixed. it failed in different dtype cases like `np.ones(np.uint8, ...)`.
I had to change `NDArray.Storage` to internal (from protected) to gain access in the backend engine.
I've added a backend method name Cast as progress with upcasting during math operations (#281).
Note: backend.Sum is still broken for types other than int32 (no due to my changes).
=> Scalar api, ndarray.sum fixed, backend casting.

src/NumSharp.Core/Backends/Unmanaged/UnmanagedStorage.Slicing.cs, src/NumSharp.Core/View/Slice.cs, test/NumSharp.UnitTest/Shape_and_Slice.Test.cs, test/NumSharp.UnitTest/View/NDArray.View.Test.cs
```C#
[TestMethod]
public void SlicingWithEllipsis()
{
var a = np.arange(16).reshape(2, 2, 2, 2);
a[Slice.Ellipsis].Should().BeOfValues(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15).And.BeShaped(2, 2, 2, 2);
a["..., 0"].Should().BeOfValues(0, 2, 4, 6, 8, 10, 12, 14).And.BeShaped(2, 2, 2);
a["0, ..."].Should().BeOfValues(0, 1, 2, 3, 4, 5, 6, 7).And.BeShaped(2, 2, 2);
a["0, ... ,0"].Should().BeOfValues(0, 2, 4, 6).And.BeShaped(2, 2);
new Action(() => a["..., 0, ..."].flatten()).Should().Throw<ArgumentException>();
}
[TestMethod]
public void SlicingWithNewAxis()
{
var a = np.arange(16).reshape(2, 2, 2, 2);
a[1, 1, np.newaxis, 1, 1].Should().BeOfValues(15).And.BeShaped(1);
a[Slice.NewAxis].Should().BeOfValues(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15).And.BeShaped(2, 2, 2, …
```
=> Slicing: implemented Ellipsis (...)

src/NumSharp.Core/APIs/np.load.cs, src/NumSharp.Core/APIs/np.save.cs, src/NumSharp.Core/Utilities/NpzDictionary.cs, test/NumSharp.UnitTest/APIs/np.load.Test.cs
I'm using NPZ files for weights. I'd like to use NumSharp for this.
* NPY supporting UInts..
* NPZ load; entry.Name -> entry.FullName
* NPZ open; using given leaveOpen value with the default of false
=> Extending NPY and fixing NPZ

src/NumSharp.Core/Creation/np.frombuffer.cs, test/NumSharp.UnitTest/Creation/np.frombuffer.Test.cs
In response to issue #423,
I added data types ( int16, int64, uint16, uint32, uint64, single and double) in method `np.frombuffer(byte[] bytes, Type dtype)` and also their corresponding unit tests.
=> Added data types in np.frombuffer.

src/NumSharp.Core/Backends/Default/Math/Default.Round.cs, src/NumSharp.Core/Backends/TensorEngine.cs, src/NumSharp.Core/Math/np.round.cs
In response to issue #452,
I added new overloads for np.around(), np.round_() and TensorEngine.Round() methods with argument decimals (int) to round the values of NDArray to user specified precision
=> Added support for user defined decimal precision for np.around() and TensorEngine.Round()
